# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
warnings_are_errors: true
cache: packages
addons:
  apt:
    packages:
      - libopenblas-dev
before_install:
  - export LD_LIBRARY_PATH="/usr/lib/openblas-base"